### ISSUE TITLE
build instruction for Ubuntu

### ISSUE THREAD

**Issue by mskyaxl** [christophediericx/AVRDisassembler#2]
it would be great if you could update the readme with some buld instructions. I would like to build it for a recent version of Ubuntu.

**Comment by mskyaxl** [comment]
The pull request  #3 solves this issue.

**Comment by christophediericx** [comment]
Thank you!

**Comment by mskyaxl** [comment]
Maybe it's worth doing another release for 0.2.1 because now all the links from the readme are pointing to it. :)
